### ISSUE TITLE
Scrub

### ISSUE THREAD

**Issue by JamesSutton** [JosephCowin/CustardQuest#3]
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}

bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}

**Comment by JamesSutton** [comment]
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}

bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}

**Comment by JamesSutton** [comment]
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}

**Comment by JamesSutton** [comment]
v
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}
bool orryIsAScrub = true;
if (orryIsAScrub = true{
Console.WriteLine("Orry is a scrub");
}

else {
Console.WriteLine("Orry is a scrub");
}
v

**Comment by OrrySwift** [comment]
hi

**Comment by OrrySwift** [comment]
get out
